[package]
name = "lts"
description = "Workaround for old Rust compiler versions. Makes Cargo see only old dependency versions, which should be compatible with old compiler versions."
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]
license = "CC0-1.0"
readme = "README.md"
keywords = ["long-term-support", "lts", "crates-io", "index", "backwards-compatibility"]
categories = ["development-tools::cargo-plugins", "configuration"]
homepage = "https://lib.rs/lts"
repository = "https://gitlab.com/kornelski/LTS"

[[bin]]
name = "cargo-lts"
path = "src/main.rs"
